[package]
name = "gambit"
version = "0.1.0"
authors = ["Sean Gillespie <sean@swgillespie.me>"]
edition = "2018"

[dependencies]
thiserror = "1.0.23" 
bitflags = "1.2.1"
lazy_static = "1.4.0"
structopt = "0.3.21"

[dev-dependencies]
criterion = "0.3"

[features]
default = []
trace-eval = []

[[bench]]
name = "position"
harness = false