name: CI

on:
  pull_request:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: Gr1N/setup-poetry@v7
      - run: poetry --version
      - run: poetry install
      - uses: actions-rs/toolchain@v1
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v1
      - name: CI
        run: python3 tools/ci.py
