name: STS
on: workflow_dispatch

jobs:
  STS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: Gr1N/setup-poetry@v7
      - run: poetry --version
      - run: poetry install
      - uses: actions-rs/toolchain@v1
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v1
      - name: Build Release
        run: cargo build --release
      - name: Run STS Tests
        run: python3 -m a4.sts -j 2 --github
